### PR TITLE
Fix misc. issues for plotly v4.

### PR DESCRIPTION
**Pull request by eholic**
I tried to fix some issues for plotly v4.

#### chart_studio https://github.com/santosjorge/cufflinks/pull/195 https://github.com/santosjorge/cufflinks/pull/198
- only replace `plotly.plotly` to `chart_studio.plotly`
#### subplots https://github.com/santosjorge/cufflinks/issues/196#issuecomment-526695267
- Variable `axe` would be [SubplotRef](https://github.com/plotly/plotly.py/blob/7cb8d6b87cbcfa477a806701c37331f953e2497e/packages/python/plotly/plotly/subplots.py#L34) in Plotly 4.
#### [Cufflinks Tutorial - Offline.ipynb](https://github.com/santosjorge/cufflinks/blob/master/Cufflinks%20Tutorial%20-%20Offline.ipynb)
- Bottom end online plot try to find filename from figure title. It still has `text` key under `title`. I don't have plotly account, has not test publishing.

#### [Cufflinks Tutorial - Quantfig.ipynb](https://github.com/santosjorge/cufflinks/blob/master/Cufflinks%20Tutorial%20-%20Quantfig.ipynb)
- `up_color` default's java is missing.

### CODE REVIEW

**Comment by nateGeorge** [comment]
How did you figure out the `_.update(axe.trace_kwargs)` part?

**Comment by eholic** [comment]
@nateGeorge Just classic print debug by comparing plotly 3 and 4 :tada:

**Comment by nicolaskruchten** [comment]
@santosjorge this one looks good to merge, and then I may have a couple of extra fixes to layer on. Shall I merge?

**Comment by nicolaskruchten** [comment]
(In the interest of time, I'll go ahead and ask for forgiveness later if required ;)

**Comment by nicolaskruchten** [comment]
Thanks very much @eholic and my apologies for not reviewing much sooner 🙏

**Comment by eholic** [comment]
Thank you for the helpful mentenances today, @nicolaskruchten . It's for me to say thank you guys for providing plotly and cufflinks!

**Pull request merged**
