### PR TITLE
Starting work on plotly 3.0.0 migration

### PR DESCRIPTION
**Pull request by timkpaine**
this is just a first pass, theres some major work to do:

- [x] 2 "FIXME TKP" sections were just commented out in plotlytools
- [x] Docstrings and defaults are wrong in many cases (e.g. "horizontal"/"vertical" not valid, "dot" not a valid marker type)
- [x] 3 "FIXME TKP" sections commented out in quant_figure
- [x] Fix JupyterLab support
    - In plotlytools, replace calls to `plot`/`iplot` with `return go.FigureWidget(data=figure['data'], layout=figure['layout'])`, not working currently for QuantFig
    - working on in https://github.com/plotly/plotly.py/issues/1071

### CODE REVIEW

**Comment by timkpaine** [comment]
should probably follow https://github.com/santosjorge/cufflinks/issues/119 and switch everything to use raw dictionaries until the last step

**Comment by timkpaine** [comment]
all the examples from the notebooks are working (albeit with warnings, also for latest pandas you need to call .mean() after resample). Need to check quantfigs (I commented out the tests for now)

**Comment by timkpaine** [comment]
shouldn't need bullet 3 https://github.com/plotly/plotly.py/issues/1071

**Comment by timkpaine** [comment]
@santosjorge this is almost done, can you do a review

**Comment by timkpaine** [comment]
this is done, just waiting on the plotly bullet but it should work

**Comment by dhirschfeld** [comment]
:beers:!

**Comment by dhirschfeld** [comment]
Confirmed that this PR works great with nteract:
image

(previously threw an exception)

**Comment by dhirschfeld** [comment]
Would love to get this functionality merged!

**Comment by dnanhkhoa** [comment]
Great, it works 👍 can't wait for merging
image

**Comment by davhin** [comment]
The cufflinks version in the pull request of timkpaine works well for me with:

plotly 3.1.0,
jupyterlab 0.34.2

and
jupyter-widgets/jupyterlab-manager v0.37.2
jupyterlab/plotly-extension v0.16.0
plotlywidget v0.2.1

Just trying to add some confidence, not meaning to confirm that it works at all ;)

**Comment by santosjorge** [comment]
Going through this PR this week. Thank you for the work so far @timkpaine !

**Comment by lilcatria** [comment]
secondary axis example seem to be breaking , 

plotly 3.1.1

```
fig=cf.datagen.lines(3,columns=['a','b','c']).figure()
fig=fig.set_axis('b',side='right')
cf.iplot(fig)
```

> AttributeError                            Traceback (most recent call last)
> <ipython-input-22-a0709b0777b1> in <module>()
>       1 fig=cf.datagen.lines(3,columns=['a','b','c']).figure()
> ----> 2 fig=fig.set_axis('b',side='right')
>       3 cf.iplot(fig)
> 
> AttributeError: 'dict' object has no attribute 'set_axis'

**Comment by timkpaine** [comment]
I'll take a look, there's one other issue I know about that I need to fix

**Comment by timkpaine** [comment]
@jonmmease

**Pull request merged**
