### PR TITLE
adding interpolation for other line types

### PR DESCRIPTION
**Pull request by timkpaine**
Take a look, adding interpolation for line charts. May require some changes, doesn't break anything I tested 

https://plot.ly/python/line-charts/#interpolation-with-line-plots

### CODE REVIEW

**Comment by santosjorge** [comment]
Excellent. Let me try this out.

**Comment by timkpaine** [comment]
@santosjorge any updates? been using this in my project for a while for step charts https://github.com/timkpaine/lantern/blob/master/lantern/plotting/plot_cufflinks.py#L143

**Comment by santosjorge** [comment]
Thank you @timkpaine !

**Comment by timkpaine** [comment]
@santosjorge thanks for the merge!

**Pull request merged**
